title: 'Plastering Brighton '
permalink: none
url: 'http://beta.abemedia.co.uk/harveysbrighton'
timezone: Europe/London
exclude:
    - Gemfile
    - Gemfile.lock
analytics:
    provider: google_analytics
defaults:
    -
        scope:
            path: ''
            type: posts
        values:
            layout: page
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
collections:
    content:
        output: true
        permalink: ':path.html'
    testimonials:
        output: true
relative_permalinks: 'false'
recaptcha_public_key: 6Lf15v0SAAAAAMReHqDCinChFIhv-Ve66By0f90D
v: 1
baseurl: /
description: 'Plastering Brighton'
comments:
    provider: '1'
sharing:
    limit: '3'
cdn: "//cdn.donlabs.com/0x0/harveysbrighton/"